### ISSUE TITLE
Welcome to hacktoberfest

### ISSUE THREAD

**Issue by ayush1612** [ayush1612/codeFury#19]

**Comment by vanishedvan** [comment]
What do I need to do?

**Comment by ayush1612** [comment]
> What do I need to do?

You need to edit the files and generate a  PR. 
Files u can easily edit:
1. data.py: add random data like you are giving a review for a course.
2. .html: try creating new elements to make the page look better
3. stylize using css

**Comment by chrysillala** [comment]
hey, if this issue still available, may i help you?

**Comment by ayush1612** [comment]
> hey, if this issue still available, may i help you?

Yeah sure.
